# Generated by Django 4.1.2 on 2023-01-28 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_rename_is_email_verified_userpet_is_email_verificado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPET',
        ),
    ]
