# Generated by Django 4.2.dev20221007110535 on 2022-10-12 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('Codigo', models.CharField(max_length=20, null=True, verbose_name='Código')),
                ('Autor', models.CharField(max_length=100)),
                ('Coautor', models.CharField(blank=True, max_length=100)),
                ('Edicao', models.IntegerField(verbose_name='Edição')),
                ('Volume', models.IntegerField(null=True)),
                ('Estado', models.CharField(choices=[('Bem conservado', 'Bem conservado'), ('Conservado', 'Conservado'), ('Pouco conservado', 'Pouco conservado')], max_length=30, null=True)),
                ('Tipo', models.CharField(choices=[('Livro', 'Livro'), ('Cópia', 'Cópia')], max_length=30, null=True)),
                ('Data', models.DateField(null=True)),
            ],
        ),
    ]
