# Generated by Django 4.1.2 on 2022-10-28 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_categoria_livro_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='livro',
            options={'ordering': ['Titulo', 'Autor']},
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descricao',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='Categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='livros.categoria'),
        ),
    ]
