# Generated by Django 4.1.2 on 2023-01-28 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0004_alter_livro_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livro',
            options={'ordering': ['Disponivel', 'Titulo', 'Autores']},
        ),
        migrations.RenameField(
            model_name='livro',
            old_name='Autor',
            new_name='Autores',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='Coautor',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='Data',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='Tipo',
        ),
        migrations.AddField(
            model_name='livro',
            name='Disponivel',
            field=models.BooleanField(default=True),
        ),
    ]
