# Generated by Django 4.1.2 on 2023-01-29 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0006_livro_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='Codigo',
            field=models.CharField(default='0000000000000', max_length=20, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='Edicao',
            field=models.IntegerField(default=0, null=True, verbose_name='Edição'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='Estado',
            field=models.CharField(choices=[('Bem conservado', 'Bem conservado'), ('Conservado', 'Conservado'), ('Pouco conservado', 'Pouco conservado')], default='Bem conservado', max_length=30),
        ),
        migrations.AlterField(
            model_name='livro',
            name='Tipo',
            field=models.CharField(choices=[('Livro', 'Livro'), ('Cópia', 'Cópia')], default='Livro', max_length=30),
        ),
        migrations.AlterField(
            model_name='livro',
            name='Volume',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
