# Generated by Django 4.1.2 on 2023-01-28 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0005_alter_livro_options_rename_autor_livro_autores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='Tipo',
            field=models.CharField(choices=[('Livro', 'Livro'), ('Cópia', 'Cópia')], max_length=30, null=True),
        ),
    ]
