# Generated by Django 4.1.5 on 2023-01-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0007_alter_livro_codigo_alter_livro_edicao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='Autores',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='Codigo',
            field=models.CharField(max_length=20, null=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='Disponivel',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='Estado',
            field=models.CharField(choices=[('Bem conservado', 'Bem conservado'), ('Conservado', 'Conservado'), ('Pouco conservado', 'Pouco conservado')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='Tipo',
            field=models.CharField(choices=[('Livro', 'Livro'), ('Cópia', 'Cópia')], default='Livro', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='Titulo',
            field=models.CharField(max_length=100, null=True, verbose_name='Título'),
        ),
    ]
