# Generated by Django 4.2.dev20221007110535 on 2022-10-25 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpet',
            old_name='is_email_verified',
            new_name='is_email_verificado',
        ),
    ]
